// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

 

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"


#include<stdio.h>
#include<stdio_ext.h>
char difference_of_string(char *s,char* t)
{
    int i=0,res=0;
    while(s[i]!='\0')
    {
        res=res^s[i];
        i++;
    }
    i=0;
    while(t[i]!='\0')
    {
        res=res^t[i];
        i++;
    }
    return res;
}
int main()
{
    char s[100],t[100],res;
    printf("enter the string1:");
    scanf("%[^\n]",s);
    __fpurge(stdin);
    printf("%s\n",s);
    printf("enter the string2: ");
    scanf("%[^\n]",t);
    printf("%s\n",t);
    res=difference_of_string(s,t); 
    printf("difference in string %c\n",res);
    return 0;


}